language: python

python:
  - "2.7"

cache:
  directories:
    - $HOME/virtualenv/python2.7.9/lib/python2.7/site-packages/numpy
    - $HOME/virtualenv/python2.7.9/lib/python2.7/site-packages/astropy
    - $HOME/.cache/pip

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - python setup.py install

script: nosetests -v
