language: python

python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv/$TRAVIS_PYTHON_VERSION/lib/$TRAVIS_PYTHON_VERSION/site-packages/numpy
    - $HOME/virtualenv/$TRAVIS_PYTHON_VERSION/lib/$TRAVIS_PYTHON_VERSION/site-packages/astropy

install:
  - pip install -r requirements.txt
  - python setup.py install

script: nosetests -v
